//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1378
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YatesMorrison.RolePlay.D20 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YatesMorrison.RolePlay.D20.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Points.
        /// </summary>
        internal static string ACTION_POINTS {
            get {
                return ResourceManager.GetString("ACTION_POINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor Penalty.
        /// </summary>
        internal static string ARMOR_PENALTY {
            get {
                return ResourceManager.GetString("ARMOR_PENALTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Attack Bonus.
        /// </summary>
        internal static string BASE_ATTACK_BONUS {
            get {
                return ResourceManager.GetString("BASE_ATTACK_BONUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charisma.
        /// </summary>
        internal static string CHA {
            get {
                return ResourceManager.GetString("CHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charisma Modifier.
        /// </summary>
        internal static string CHA_MOD {
            get {
                return ResourceManager.GetString("CHA_MOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        internal static string CLASS_BASE {
            get {
                return ResourceManager.GetString("CLASS_BASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charismatic.
        /// </summary>
        internal static string CLASS_CHARISMATIC {
            get {
                return ResourceManager.GetString("CLASS_CHARISMATIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dedicated.
        /// </summary>
        internal static string CLASS_DEDICATED {
            get {
                return ResourceManager.GetString("CLASS_DEDICATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast.
        /// </summary>
        internal static string CLASS_FAST {
            get {
                return ResourceManager.GetString("CLASS_FAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart.
        /// </summary>
        internal static string CLASS_SMART {
            get {
                return ResourceManager.GetString("CLASS_SMART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong.
        /// </summary>
        internal static string CLASS_STRONG {
            get {
                return ResourceManager.GetString("CLASS_STRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tough.
        /// </summary>
        internal static string CLASS_TOUGH {
            get {
                return ResourceManager.GetString("CLASS_TOUGH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constitution.
        /// </summary>
        internal static string CON {
            get {
                return ResourceManager.GetString("CON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constitution Modifier.
        /// </summary>
        internal static string CON_MOD {
            get {
                return ResourceManager.GetString("CON_MOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defense Bonus.
        /// </summary>
        internal static string DEFENSE_BONUS {
            get {
                return ResourceManager.GetString("DEFENSE_BONUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dexterity.
        /// </summary>
        internal static string DEX {
            get {
                return ResourceManager.GetString("DEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dexterity Modifier.
        /// </summary>
        internal static string DEX_MOD {
            get {
                return ResourceManager.GetString("DEX_MOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Bonus.
        /// </summary>
        internal static string EQUIP_BONUS {
            get {
                return ResourceManager.GetString("EQUIP_BONUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fortitude Save.
        /// </summary>
        internal static string FORTITUDE_SAVE {
            get {
                return ResourceManager.GetString("FORTITUDE_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit Points.
        /// </summary>
        internal static string HP {
            get {
                return ResourceManager.GetString("HP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initiative Modifier.
        /// </summary>
        internal static string INITIATIVE {
            get {
                return ResourceManager.GetString("INITIATIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligence.
        /// </summary>
        internal static string INT {
            get {
                return ResourceManager.GetString("INT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligence Modifier.
        /// </summary>
        internal static string INT_MOD {
            get {
                return ResourceManager.GetString("INT_MOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melee Attack Bonus.
        /// </summary>
        internal static string MELEE_ATTACK_BONUS {
            get {
                return ResourceManager.GetString("MELEE_ATTACK_BONUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranged Attack Bonus.
        /// </summary>
        internal static string RANGED_ATTACK_BONUS {
            get {
                return ResourceManager.GetString("RANGED_ATTACK_BONUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reflex Save.
        /// </summary>
        internal static string REFLEX_SAVE {
            get {
                return ResourceManager.GetString("REFLEX_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reputation Bonus.
        /// </summary>
        internal static string REPUTATION {
            get {
                return ResourceManager.GetString("REPUTATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string SIZE {
            get {
                return ResourceManager.GetString("SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size Modifier.
        /// </summary>
        internal static string SIZE_MOD {
            get {
                return ResourceManager.GetString("SIZE_MOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string SKILL_BALANCE {
            get {
                return ResourceManager.GetString("SKILL_BALANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluff.
        /// </summary>
        internal static string SKILL_BLUFF {
            get {
                return ResourceManager.GetString("SKILL_BLUFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer Use.
        /// </summary>
        internal static string SKILL_COMPUTER_USE {
            get {
                return ResourceManager.GetString("SKILL_COMPUTER_USE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concentration.
        /// </summary>
        internal static string SKILL_CONCENTRATION {
            get {
                return ResourceManager.GetString("SKILL_CONCENTRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Craft: Mechanical.
        /// </summary>
        internal static string SKILL_CRAFT_MECHANICAL {
            get {
                return ResourceManager.GetString("SKILL_CRAFT_MECHANICAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Craft: Pharmeceutical.
        /// </summary>
        internal static string SKILL_CRAFT_PHARMECEUTICAL {
            get {
                return ResourceManager.GetString("SKILL_CRAFT_PHARMECEUTICAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decipher Script.
        /// </summary>
        internal static string SKILL_DECIPHER_SCRIPT {
            get {
                return ResourceManager.GetString("SKILL_DECIPHER_SCRIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demolitions.
        /// </summary>
        internal static string SKILL_DEMOLITIONS {
            get {
                return ResourceManager.GetString("SKILL_DEMOLITIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diplomacy.
        /// </summary>
        internal static string SKILL_DIPLOMACY {
            get {
                return ResourceManager.GetString("SKILL_DIPLOMACY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Device.
        /// </summary>
        internal static string SKILL_DISABLE_DEVICE {
            get {
                return ResourceManager.GetString("SKILL_DISABLE_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disguise.
        /// </summary>
        internal static string SKILL_DISGUISE {
            get {
                return ResourceManager.GetString("SKILL_DISGUISE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive.
        /// </summary>
        internal static string SKILL_DRIVE {
            get {
                return ResourceManager.GetString("SKILL_DRIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escape Artist.
        /// </summary>
        internal static string SKILL_ESCAPE_ARTIST {
            get {
                return ResourceManager.GetString("SKILL_ESCAPE_ARTIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgery.
        /// </summary>
        internal static string SKILL_FORGERY {
            get {
                return ResourceManager.GetString("SKILL_FORGERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamble.
        /// </summary>
        internal static string SKILL_GAMBLE {
            get {
                return ResourceManager.GetString("SKILL_GAMBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gather Information.
        /// </summary>
        internal static string SKILL_GATHER_INFORMATION {
            get {
                return ResourceManager.GetString("SKILL_GATHER_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handle Animal.
        /// </summary>
        internal static string SKILL_HANDLE_ANIMAL {
            get {
                return ResourceManager.GetString("SKILL_HANDLE_ANIMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string SKILL_HIDE {
            get {
                return ResourceManager.GetString("SKILL_HIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intimidate.
        /// </summary>
        internal static string SKILL_INTIMIDATE {
            get {
                return ResourceManager.GetString("SKILL_INTIMIDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investigate.
        /// </summary>
        internal static string SKILL_INVESTIGATE {
            get {
                return ResourceManager.GetString("SKILL_INVESTIGATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump.
        /// </summary>
        internal static string SKILL_JUMP {
            get {
                return ResourceManager.GetString("SKILL_JUMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knowledge: Current Events.
        /// </summary>
        internal static string SKILL_KNOWLEDGE_CURRENT_EVENTS {
            get {
                return ResourceManager.GetString("SKILL_KNOWLEDGE_CURRENT_EVENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knowledge: Popular Culture.
        /// </summary>
        internal static string SKILL_KNOWLEDGE_POPULAR_CULTURE {
            get {
                return ResourceManager.GetString("SKILL_KNOWLEDGE_POPULAR_CULTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knowledge: Streetwise.
        /// </summary>
        internal static string SKILL_KNOWLEDGE_STREETWISE {
            get {
                return ResourceManager.GetString("SKILL_KNOWLEDGE_STREETWISE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen.
        /// </summary>
        internal static string SKILL_LISTEN {
            get {
                return ResourceManager.GetString("SKILL_LISTEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Silently.
        /// </summary>
        internal static string SKILL_MOVE_SILENTLY {
            get {
                return ResourceManager.GetString("SKILL_MOVE_SILENTLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate.
        /// </summary>
        internal static string SKILL_NAVIGATE {
            get {
                return ResourceManager.GetString("SKILL_NAVIGATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pilot.
        /// </summary>
        internal static string SKILL_PILOT {
            get {
                return ResourceManager.GetString("SKILL_PILOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profession.
        /// </summary>
        internal static string SKILL_PROFESSION {
            get {
                return ResourceManager.GetString("SKILL_PROFESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair.
        /// </summary>
        internal static string SKILL_REPAIR {
            get {
                return ResourceManager.GetString("SKILL_REPAIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research.
        /// </summary>
        internal static string SKILL_RESEARCH {
            get {
                return ResourceManager.GetString("SKILL_RESEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ride.
        /// </summary>
        internal static string SKILL_RIDE {
            get {
                return ResourceManager.GetString("SKILL_RIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SKILL_SEARCH {
            get {
                return ResourceManager.GetString("SKILL_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sense Motive.
        /// </summary>
        internal static string SKILL_SENSE_MOTIVE {
            get {
                return ResourceManager.GetString("SKILL_SENSE_MOTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleight Of Hand.
        /// </summary>
        internal static string SKILL_SLEIGHT_OF_HAND {
            get {
                return ResourceManager.GetString("SKILL_SLEIGHT_OF_HAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spot.
        /// </summary>
        internal static string SKILL_SPOT {
            get {
                return ResourceManager.GetString("SKILL_SPOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survival.
        /// </summary>
        internal static string SKILL_SURVIVAL {
            get {
                return ResourceManager.GetString("SKILL_SURVIVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swim.
        /// </summary>
        internal static string SKILL_SWIM {
            get {
                return ResourceManager.GetString("SKILL_SWIM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treat Injury.
        /// </summary>
        internal static string SKILL_TREAT_INJURY {
            get {
                return ResourceManager.GetString("SKILL_TREAT_INJURY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tumble.
        /// </summary>
        internal static string SKILL_TUMBLE {
            get {
                return ResourceManager.GetString("SKILL_TUMBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        internal static string SPEED {
            get {
                return ResourceManager.GetString("SPEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength.
        /// </summary>
        internal static string STR {
            get {
                return ResourceManager.GetString("STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength Modifier.
        /// </summary>
        internal static string STR_MOD {
            get {
                return ResourceManager.GetString("STR_MOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wealth Bonus.
        /// </summary>
        internal static string WEALTH_BONUS {
            get {
                return ResourceManager.GetString("WEALTH_BONUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will Save.
        /// </summary>
        internal static string WILL_SAVE {
            get {
                return ResourceManager.GetString("WILL_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wisdom.
        /// </summary>
        internal static string WIS {
            get {
                return ResourceManager.GetString("WIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wisdom Modifier.
        /// </summary>
        internal static string WIS_MOD {
            get {
                return ResourceManager.GetString("WIS_MOD", resourceCulture);
            }
        }
    }
}
