<?xml version="1.0" encoding="utf-8"?>
<Database Name="RpgNet.Application" Class="RpgNetModelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=RpgNet.Application;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="RpgNet_ApplicationConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Actor" Member="Actors">
    <Type Name="Actor">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PlayerFK" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CharacterClassFK" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RaceFK" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DeityFK" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GroupFK" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Strength" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Constitution" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Dexterity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Intelligence" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Wisdom" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Charisma" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Wealth" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Experience" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Gender" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Height" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Weight" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Alignment" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Milestones" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PersonalityTraits" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MannerismsAndAppearance" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Background" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="OtherEquipment" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Actor_ActorBonus" Member="ActorBonus" OtherKey="ActorIdFk" Type="ActorBonus" />
      <Association Name="Actor_ActorFeat" Member="ActorFeats" OtherKey="ActorIdFk" Type="ActorFeat" />
      <Association Name="Actor_ActorPower" Member="ActorPowers" OtherKey="ActorIdFk" Type="ActorPower" />
      <Association Name="Actor_ActorSkill" Member="ActorSkills" OtherKey="ActorIdFk" Type="ActorSkill" />
      <Association Name="Race_Actor" Member="Race" ThisKey="RaceFK" Type="Race" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="CharacterClass_Actor" Member="CharacterClass" ThisKey="CharacterClassFK" Type="CharacterClass" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="Deity_Actor" Member="Deity" ThisKey="DeityFK" Type="Deity" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="Player_Actor" Member="Player" ThisKey="PlayerFK" Type="Player" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Race" Member="Races">
    <Type Name="Race">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Size" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Association Name="Race_Actor" Member="Actors" OtherKey="RaceFK" Type="Actor" />
    </Type>
  </Table>
  <Table Name="dbo.ActorBonus" Member="ActorBonus">
    <Type Name="ActorBonus">
      <Column Name="ActorIdFk" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Bonus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Actor_ActorBonus" Member="Actor" ThisKey="ActorIdFk" Type="Actor" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ActorFeat" Member="ActorFeats">
    <Type Name="ActorFeat">
      <Column Name="ActorIdFk" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FeatIdFk" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Target" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Actor_ActorFeat" Member="Actor" ThisKey="ActorIdFk" Type="Actor" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Feat_ActorFeat" Member="Feat" ThisKey="FeatIdFk" Type="Feat" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ActorPower" Member="ActorPowers">
    <Type Name="ActorPower">
      <Column Name="ActorIdFk" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PowerIdFk" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Actor_ActorPower" Member="Actor" ThisKey="ActorIdFk" Type="Actor" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Power_ActorPower" Member="Power" ThisKey="PowerIdFk" Type="Power" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ActorSkill" Member="ActorSkills">
    <Type Name="ActorSkill">
      <Column Name="ActorIdFk" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SkillIdFk" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Trained" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Actor_ActorSkill" Member="Actor" ThisKey="ActorIdFk" Type="Actor" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CharacterClass" Member="CharacterClasses">
    <Type Name="CharacterClass">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="CharacterClass_Actor" Member="Actors" OtherKey="CharacterClassFK" Type="Actor" />
    </Type>
  </Table>
  <Table Name="dbo.Deity" Member="Deities">
    <Type Name="Deity">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Deity_Actor" Member="Actors" OtherKey="DeityFK" Type="Actor" />
    </Type>
  </Table>
  <Table Name="dbo.Feat" Member="Feats">
    <Type Name="Feat">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IsRepeatable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Feat_ActorFeat" Member="ActorFeats" OtherKey="FeatIdFk" Type="ActorFeat" />
    </Type>
  </Table>
  <Table Name="dbo.Player" Member="Players">
    <Type Name="Player">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Player_Actor" Member="Actors" OtherKey="PlayerFK" Type="Actor" />
    </Type>
  </Table>
  <Table Name="dbo.Power" Member="Powers">
    <Type Name="Power">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Level]" Member="Level" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Type" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Action" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Keywords" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FlavorText" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Power_ActorPower" Member="ActorPowers" OtherKey="PowerIdFk" Type="ActorPower" />
    </Type>
  </Table>
</Database>